CREATE TABLE USERS
(
    ID                BIGSERIAL PRIMARY KEY,
    EMAIL             VARCHAR(128) UNIQUE NOT NULL,
    EMAIL_VERIFIED    BOOLEAN             NOT NULL,
    LAST_LOGIN        TIMESTAMP           NOT NULL,
    PHONE_NUMBER      VARCHAR(128) UNIQUE NOT NULL,
    PASSWORD          VARCHAR(128)        NOT NULL,
    REGISTRATION_DATE TIMESTAMP           NOT NULL,
    BIRTH_DATE        DATE                NOT NULL,
    FIRST_NAME        VARCHAR(128),
    LAST_NAME         VARCHAR(128),
    IMAGE             VARCHAR(128),
    ACTIVITY          VARCHAR(128)        NOT NULL,
    ROLE              VARCHAR(128)        NOT NULL
);

CREATE TABLE ADDRESS
(
    ID               BIGSERIAL PRIMARY KEY,
    USER_ID          BIGINT       NOT NULL REFERENCES USERS (ID),
    COUNTRY          VARCHAR(128) NOT NULL,
    CITY             VARCHAR(128) NOT NULL,
    STREET           VARCHAR(128) NOT NULL,
    HOUSE_NUMBER     INT          NOT NULL,
    APARTMENT_NUMBER INT
);

CREATE TABLE SHOPPING_CART
(
    ID           BIGSERIAL PRIMARY KEY,
    USER_ID      BIGINT REFERENCES USERS (ID) NOT NULL,
    ORDER_STATUS VARCHAR(128)                NOT NULL,
    CREATE_TIME  TIMESTAMP                   NOT NULL,
    UPDATE_TIME  TIMESTAMP                   NOT NULL
);

CREATE TABLE SHOPPING_CART_PRODUCT
(
    ID               BIGSERIAL PRIMARY KEY,
    SHOPPING_CART_ID BIGINT,
    PRODUCT_ID       BIGINT,
    COUNT_PRODUCT    INT NOT NULL CHECK (COUNT_PRODUCT > 0),
    FOREIGN KEY (SHOPPING_CART_ID) REFERENCES SHOPPING_CART (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE PRODUCT
(
    ID            BIGSERIAL PRIMARY KEY,
    PRICE         DECIMAL CHECK (PRICE > 0) NOT NULL,
    CREATE_AT     TIMESTAMP                 NOT NULL,
    AVAILABLE     BOOLEAN                   NOT NULL,
    DESCRIPTION   VARCHAR(128)              NOT NULL,
    CATEGORY      VARCHAR(128)              NOT NULL,
    COUNT         INT CHECK (COUNT >= 0)    NOT NULL,
    PRODUCT_IMAGE VARCHAR(128)
);

CREATE TABLE PRODUCT_REVIEW
(
    ID          BIGSERIAL PRIMARY KEY,
    PRODUCT_ID  BIGINT REFERENCES PRODUCT (ID) NOT NULL,
    CREATE_TIME TIMESTAMP                      NOT NULL,
    USER_ID     BIGINT REFERENCES USERS (ID)   NOT NULL,
    DESCRIPTION VARCHAR(128),
    IMAGE       VARCHAR(128),
    RATING      INT CHECK (RATING BETWEEN 1 AND 5) NOT NULL
);

CREATE TABLE PROMO_CODE
(
    ID                 BIGSERIAL PRIMARY KEY,
    CODE               VARCHAR(128) UNIQUE                   NOT NULL,
    DISCOUNT_SUM       NUMERIC CHECK (DISCOUNT_SUM >= 0)     NOT NULL,
    REMAINING_QUANTITY INT CHECK (REMAINING_QUANTITY >= 0)   NOT NULL,
    ACTIVITY_PROMO     BOOLEAN                               NOT NULL,
    MIN_ORDER_AMOUNT   NUMERIC CHECK (MIN_ORDER_AMOUNT >= 0) NOT NULL,
    VALID_TO           TIMESTAMP                             NOT NULL,
    VALID_FROM         TIMESTAMP                             NOT NULL
);

CREATE TABLE USER_PROMO_CODE
(
    ID            BIGSERIAL PRIMARY KEY,
    USER_ID       BIGINT NOT NULL,
    PROMO_CODE_ID BIGINT NOT NULL,
    USED_AT       TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (PROMO_CODE_ID) REFERENCES PROMO_CODE (ID)
);